// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class ApiResourceSecretsConfiguration : IEntityTypeConfiguration<ApiResourceSecrets>
    {
        public void Configure(EntityTypeBuilder<ApiResourceSecrets> entity)
        {
            entity.HasIndex(e => e.ApiResourceId);
        }
    }
}
