// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class ApiScopesConfiguration : IEntityTypeConfiguration<ApiScopes>
    {
        public void Configure(EntityTypeBuilder<ApiScopes> entity)
        {
            entity.HasIndex(e => e.Name)
                .IsUnique();
        }
    }
}
