// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class PersistedGrantsConfiguration : IEntityTypeConfiguration<PersistedGrants>
    {
        public void Configure(EntityTypeBuilder<PersistedGrants> entity)
        {
            entity.HasIndex(e => e.Expiration);

            entity.HasIndex(e => new { e.SubjectId, e.ClientId, e.Type });

            entity.HasIndex(e => new { e.SubjectId, e.SessionId, e.Type });
        }
    }
}
