// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdCompanyConfiguration : IEntityTypeConfiguration<psAdCompany>
    {
        public void Configure(EntityTypeBuilder<psAdCompany> entity)
        {
            entity.Property(e => e.dStampDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iConcurrency)
                .HasDefaultValueSql("((0))")
                .HasComment("This field is set to 1 immediately a user edits it.By default its 0.");

            entity.Property(e => e.iStatus)
                .HasDefaultValueSql("((0))")
                .HasComment("This filed describes the status of a record whether in-use or not-in-use");

            entity.Property(e => e.iUserId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.szCompanyName).IsUnicode(false);
        }
    }
}
