// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psAdUserGroup_Log
    {
        [Key]
        public long pkId { get; set; }
        public long ID { get; set; }
        [Required]
        [StringLength(50)]
        public string szGroupName { get; set; }
        [Required]
        public string szCompanyId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dCreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dStampDate { get; set; }
        [Required]
        public string szUserId { get; set; }
        [StringLength(20)]
        public string szStatus { get; set; }
    }
}