// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdUserConfiguration : IEntityTypeConfiguration<psAdUser>
    {
        public void Configure(EntityTypeBuilder<psAdUser> entity)
        {
            entity.HasKey(e => e.pkId)
                .HasName("PK_Table_1");

            entity.Property(e => e.dCreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.dStampDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iFirstTimeLogin)
                .HasDefaultValueSql("((0))")
                .HasComment("0 means this is a new account and 1 means changed password");
        }
    }
}
