// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdRegistryConfiguration : IEntityTypeConfiguration<psAdRegistry>
    {
        public void Configure(EntityTypeBuilder<psAdRegistry> entity)
        {
            entity.Property(e => e.szDataPath)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szInitialCatalog)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szPicturePath)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szReportPath)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szSSPI)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szServerName)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szTextPath)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szUserId).IsUnicode(false);
        }
    }
}
