// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psAdCompany
    {
        [Key]
        public long pkId { get; set; }
        public long iAccountId { get; set; }
        [Required]
        public string szCompanyName { get; set; }
        public int? iStatus { get; set; }
        public int? iConcurrency { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dStampDate { get; set; }
        public long iUserId { get; set; }
        public int iNoOfEmployees { get; set; }
        public Guid? uCompanyId { get; set; }
        [StringLength(10)]
        public string szCode { get; set; }
    }
}