// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdSegmentTransConfiguration : IEntityTypeConfiguration<psAdSegmentTrans>
    {
        public void Configure(EntityTypeBuilder<psAdSegmentTrans> entity)
        {
            entity.Property(e => e.dStampDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iUserId).HasDefaultValueSql("((-1))");
        }
    }
}
