// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psAdPersonnelRequest
    {
        [Key]
        public long pkId { get; set; }
        public long iUserRequestId { get; set; }
        [Required]
        [StringLength(50)]
        public string szUserName { get; set; }
        [Required]
        [StringLength(100)]
        public string szFirstName { get; set; }
        [Required]
        [StringLength(100)]
        public string szLastName { get; set; }
        [Required]
        [StringLength(100)]
        public string szEmailAddress { get; set; }
        [Column(TypeName = "text")]
        public string szImage { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dStampdate { get; set; }
        public long? iEmployeeID { get; set; }
    }
}