// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdPersonnelConfiguration : IEntityTypeConfiguration<psAdPersonnel>
    {
        public void Configure(EntityTypeBuilder<psAdPersonnel> entity)
        {
            entity.HasKey(e => e.pkId)
                .HasName("PK_Personnel_1");

            entity.Property(e => e.szEmailAddress).IsUnicode(false);

            entity.Property(e => e.szFirstName).IsUnicode(false);

            entity.Property(e => e.szLastName).IsUnicode(false);

            entity.Property(e => e.szType).IsUnicode(false);

            entity.Property(e => e.szUserName).IsUnicode(false);
        }
    }
}
