// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psAdUser
    {
        [Key]
        public long pkId { get; set; }
        public long iGroupId { get; set; }
        public long iPersonelId { get; set; }
        public byte[] szPassword { get; set; }
        [Column(TypeName = "xml")]
        public string szHashKey { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dCreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dStampDate { get; set; }
        public long? iUserId { get; set; }
        public int? iStatus { get; set; }
        public int? iConcurrency { get; set; }
        public int? iFirstTimeLogin { get; set; }
    }
}