// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdAccountConfiguration : IEntityTypeConfiguration<psAdAccount>
    {
        public void Configure(EntityTypeBuilder<psAdAccount> entity)
        {
            entity.Property(e => e.dStampDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iNoOfCompanies).HasDefaultValueSql("((0))");

            entity.Property(e => e.szAccountId)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szAccountName)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szAddress).IsUnicode(false);

            entity.Property(e => e.szContactCell).IsUnicode(false);

            entity.Property(e => e.szContactEmail).IsUnicode(false);

            entity.Property(e => e.szContactFirstName).IsUnicode(false);

            entity.Property(e => e.szContactLastName).IsUnicode(false);

            entity.Property(e => e.szContactPhone).IsUnicode(false);

            entity.Property(e => e.szFax).IsUnicode(false);

            entity.Property(e => e.szHarewareKey).IsUnicode(false);

            entity.Property(e => e.szLogo).IsUnicode(false);

            entity.Property(e => e.szRegKey)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szWebsite).IsUnicode(false);
        }
    }
}
