// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdPersonelAppReqRightsConfiguration : IEntityTypeConfiguration<psAdPersonelAppReqRights>
    {
        public void Configure(EntityTypeBuilder<psAdPersonelAppReqRights> entity)
        {
            entity.HasKey(e => e.pkId)
                .HasName("PK__psAdPers__40A359C3EEAF865E");

            entity.Property(e => e.dCreatedate).HasDefaultValueSql("(getdate())");
        }
    }
}
