// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdPersonnelRequestConfiguration : IEntityTypeConfiguration<psAdPersonnelRequest>
    {
        public void Configure(EntityTypeBuilder<psAdPersonnelRequest> entity)
        {
            entity.Property(e => e.dStampdate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iEmployeeID).HasDefaultValueSql("((0))");

            entity.Property(e => e.szEmailAddress).IsUnicode(false);

            entity.Property(e => e.szFirstName).IsUnicode(false);

            entity.Property(e => e.szImage).HasDefaultValueSql("('')");

            entity.Property(e => e.szLastName).IsUnicode(false);

            entity.Property(e => e.szUserName).IsUnicode(false);
        }
    }
}
