// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psAdRegistry
    {
        [Key]
        public long pkId { get; set; }
        public long iAccountId { get; set; }
        [Required]
        [StringLength(50)]
        public string szServerName { get; set; }
        public string szReportPath { get; set; }
        public string szPicturePath { get; set; }
        public string szTextPath { get; set; }
        public string szInitialCatalog { get; set; }
        [StringLength(20)]
        public string szSSPI { get; set; }
        public string szDataPath { get; set; }
        [Required]
        [StringLength(20)]
        public string szUserId { get; set; }
    }
}