// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdReportFilterConfiguration : IEntityTypeConfiguration<psAdReportFilter>
    {
        public void Configure(EntityTypeBuilder<psAdReportFilter> entity)
        {
            entity.Property(e => e.dCreatedate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iRequire).HasDefaultValueSql("((0))");

            entity.Property(e => e.szDataType).IsUnicode(false);

            entity.Property(e => e.szField)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");
        }
    }
}
