// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAdUserApp_LogConfiguration : IEntityTypeConfiguration<psAdUserApp_Log>
    {
        public void Configure(EntityTypeBuilder<psAdUserApp_Log> entity)
        {
            entity.Property(e => e.dCreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.dStampDate).HasDefaultValueSql("(getdate())");
        }
    }
}
