// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psAssembly
    {
        [Key]
        public Guid pkId { get; set; }
        [StringLength(50)]
        public string szAssemblyName { get; set; }
        public string szLogo { get; set; }
        public string szUrl { get; set; }
        public string szServerName { get; set; }
        public string szDatabaseUserId { get; set; }
        public string szDatabasePassword { get; set; }
        [StringLength(100)]
        public string szDatabaseName { get; set; }
        public bool? bMultipleActiveResultSets { get; set; }
        public Guid? iUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dCreateDate { get; set; }
        [StringLength(10)]
        public string szCode { get; set; }
    }
}