// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psAuthorisation
    {
        [Key]
        public int pkId { get; set; }
        public Guid uniqueId { get; set; }
        [Required]
        [StringLength(150)]
        public string szName { get; set; }
        [Required]
        [StringLength(100)]
        public string szEmailAddress { get; set; }
        public int iStatus { get; set; }
        public long iUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dCreateDate { get; set; }
        public long iPersonalId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime dUpdateDate { get; set; }
        public long iUpdateUserId { get; set; }
    }
}