// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAuthorisationConfiguration : IEntityTypeConfiguration<psAuthorisation>
    {
        public void Configure(EntityTypeBuilder<psAuthorisation> entity)
        {
            entity.HasKey(e => e.pkId)
                .HasName("PK__psAuthor__40A359C3E08F7318");

            entity.Property(e => e.dCreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.dUpdateDate).HasDefaultValueSql("('')");

            entity.Property(e => e.iPersonalId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.iUpdateUserId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.szEmailAddress).IsUnicode(false);

            entity.Property(e => e.szName).IsUnicode(false);

            entity.Property(e => e.uniqueId).HasDefaultValueSql("(newid())");
        }
    }
}
