// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psAuditTrail
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(150)]
        public string szUserId { get; set; }
        [Required]
        [StringLength(250)]
        public string szFunction { get; set; }
        public int iSuccessId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dCreatedate { get; set; }
        [StringLength(200)]
        public string szDeviceId { get; set; }
    }
}