// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psAuditTrailConfiguration : IEntityTypeConfiguration<psAuditTrail>
    {
        public void Configure(EntityTypeBuilder<psAuditTrail> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.szDeviceId).IsUnicode(false);

            entity.Property(e => e.szFunction).IsUnicode(false);

            entity.Property(e => e.szUserId).IsUnicode(false);
        }
    }
}
