// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psDevice
    {
        [Key]
        public Guid pkId { get; set; }
        public long? szImeiNumber { get; set; }
        [StringLength(50)]
        public string szBrand { get; set; }
        [StringLength(50)]
        public string szModel { get; set; }
        public Guid? iAssembly { get; set; }
        public Guid? iUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dCreateDate { get; set; }
    }
}