// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psExchangeRate_LogConfiguration : IEntityTypeConfiguration<psExchangeRate_Log>
    {
        public void Configure(EntityTypeBuilder<psExchangeRate_Log> entity)
        {
            entity.Property(e => e.Id).HasDefaultValueSql("((-1))");

            entity.Property(e => e.dExchangeRateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.szCurrency)
                .IsUnicode(false)
                .HasDefaultValueSql("((-1))");

            entity.Property(e => e.szUserId)
                .IsUnicode(false)
                .HasDefaultValueSql("((-1))");
        }
    }
}
