// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psLogs
    {
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Required]
        [StringLength(255)]
        public string Thread { get; set; }
        [Required]
        [StringLength(50)]
        public string Level { get; set; }
        [Required]
        [StringLength(255)]
        public string Logger { get; set; }
        [Required]
        public string Message { get; set; }
        public string Exception { get; set; }
    }
}