// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psUserRequestConfiguration : IEntityTypeConfiguration<psUserRequest>
    {
        public void Configure(EntityTypeBuilder<psUserRequest> entity)
        {
            entity.Property(e => e.dCreatedate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.dRequestdate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iAdminUserId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.iApplicationId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.iConfirmedBy).HasDefaultValueSql("((-1))");

            entity.Property(e => e.iRequestTypeId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.iRequesterId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.iStatus).HasDefaultValueSql("((1))");

            entity.Property(e => e.szConfirmedComment)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szRequesterComment)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");
        }
    }
}
