// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class psUserActionConfiguration : IEntityTypeConfiguration<psUserAction>
    {
        public void Configure(EntityTypeBuilder<psUserAction> entity)
        {
            entity.Property(e => e.bLogin).HasDefaultValueSql("((-1))");

            entity.Property(e => e.dActionDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iAppId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.iUserId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.szUserAction).IsUnicode(false);
        }
    }
}
