// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psUserRequest
    {
        [Key]
        public long pkId { get; set; }
        public long? iRequestTypeId { get; set; }
        public long? iRequesterId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dRequestdate { get; set; }
        public long? iConfirmedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dConfirmeddate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dCreatedate { get; set; }
        public int iStatus { get; set; }
        public string szRequesterComment { get; set; }
        public string szConfirmedComment { get; set; }
        public long iAdminUserId { get; set; }
        public int iApplicationId { get; set; }
    }
}