// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class psUserAction
    {
        [Key]
        public long pkId { get; set; }
        public long iUserId { get; set; }
        public long iAppId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dActionDate { get; set; }
        public bool? bLogin { get; set; }
        [StringLength(100)]
        public string szUserAction { get; set; }
    }
}