// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class spAppsConfiguration : IEntityTypeConfiguration<spApps>
    {
        public void Configure(EntityTypeBuilder<spApps> entity)
        {
            entity.Property(e => e.dCreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iProjectId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.szDescription)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szName).HasDefaultValueSql("('')");

            entity.Property(e => e.szPrefix)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.szURL).HasDefaultValueSql("('')");
        }
    }
}
