// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class spApps
    {
        [Key]
        public int pkId { get; set; }
        [Required]
        [StringLength(100)]
        public string szName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime dCreateDate { get; set; }
        [Required]
        [StringLength(10)]
        public string szPrefix { get; set; }
        [StringLength(250)]
        public string szURL { get; set; }
        [StringLength(200)]
        public string szDescription { get; set; }
        public long? iProjectId { get; set; }
    }
}