// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class spAuthLevelConfiguration : IEntityTypeConfiguration<spAuthLevel>
    {
        public void Configure(EntityTypeBuilder<spAuthLevel> entity)
        {
            entity.HasKey(e => e.pkID)
                .HasName("PK_psAuthLevel");

            entity.Property(e => e.pkID).ValueGeneratedNever();

            entity.Property(e => e.szCode).IsUnicode(false);

            entity.Property(e => e.szName).IsUnicode(false);
        }
    }
}
