// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class spAuthorizationConfiguration : IEntityTypeConfiguration<spAuthorization>
    {
        public void Configure(EntityTypeBuilder<spAuthorization> entity)
        {
            entity.HasNoKey();

            entity.Property(e => e.bAllowed).HasDefaultValueSql("((0))");

            entity.Property(e => e.pkID).ValueGeneratedOnAdd();

            entity.Property(e => e.szType).IsUnicode(false);
        }
    }
}
