// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class spAuthorization
    {
        public int pkID { get; set; }
        public int iGroup { get; set; }
        [StringLength(50)]
        public string szType { get; set; }
        public int? iACL { get; set; }
        public bool? bAllowed { get; set; }
    }
}