// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class spGroupAuthConfiguration : IEntityTypeConfiguration<spGroupAuth>
    {
        public void Configure(EntityTypeBuilder<spGroupAuth> entity)
        {
            entity.HasKey(e => e.pkID)
                .HasName("PK_psGroupAuth");

            entity.Property(e => e.szName).IsUnicode(false);
        }
    }
}
