// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class spPersonnelConfiguration : IEntityTypeConfiguration<spPersonnel>
    {
        public void Configure(EntityTypeBuilder<spPersonnel> entity)
        {
            entity.HasKey(e => e.pkID)
                .HasName("PK_Personnel");

            entity.Property(e => e.dStampDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iConcurrency)
                .HasDefaultValueSql("((0))")
                .HasComment("This field is set to 1 immediately a user edits it.By default its 0.");

            entity.Property(e => e.iEmployeeID).HasDefaultValueSql("((-1))");

            entity.Property(e => e.iUserID).HasDefaultValueSql("((-1))");

            entity.Property(e => e.szEmailAddress).IsUnicode(false);

            entity.Property(e => e.szFirstName).IsUnicode(false);

            entity.Property(e => e.szLastName).IsUnicode(false);

            entity.Property(e => e.szType).IsUnicode(false);

            entity.Property(e => e.szUserName)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");
        }
    }
}
