// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class spProjects
    {
        [Key]
        public long pkId { get; set; }
        [Required]
        public string szProjectName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dCreatedate { get; set; }
        public string szDescription { get; set; }
        public Guid? szUniqueIdentifier { get; set; }
    }
}