// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Admin.IDP.Entity
{
    public partial class spReportFilterOptions
    {
        [Key]
        public long pkId { get; set; }
        public long iReportFilterId { get; set; }
        public long iOperatorId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dCreatedate { get; set; }
    }
}