// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class spReportItemsConfiguration : IEntityTypeConfiguration<spReportItems>
    {
        public void Configure(EntityTypeBuilder<spReportItems> entity)
        {
            entity.Property(e => e.dCreatedate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iProjectId).HasDefaultValueSql("((-1))");

            entity.Property(e => e.szItemDescription).IsUnicode(false);

            entity.Property(e => e.szOperator).HasDefaultValueSql("('')");

            entity.Property(e => e.szType).IsUnicode(false);
        }
    }
}
