// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class spStringsConfiguration : IEntityTypeConfiguration<spStrings>
    {
        public void Configure(EntityTypeBuilder<spStrings> entity)
        {
            entity.HasKey(e => e.pkID)
                .HasName("PK_sString");

            entity.Property(e => e.dCreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.dStampDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.iApplication).HasDefaultValueSql("((-1))");

            entity.Property(e => e.iParent).HasDefaultValueSql("((0))");

            entity.Property(e => e.iStatus).HasDefaultValueSql("((-1))");

            entity.Property(e => e.szDesc)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.szEnglish).HasDefaultValueSql("('')");

            entity.Property(e => e.szFrench).HasDefaultValueSql("('')");

            entity.Property(e => e.szOtherLanguage).HasDefaultValueSql("('')");

            entity.Property(e => e.szParent).HasDefaultValueSql("('')");

            entity.Property(e => e.szPortuguese).HasDefaultValueSql("('')");

            entity.Property(e => e.szSpanish).HasDefaultValueSql("('')");

            entity.Property(e => e.szType)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");
        }
    }
}
