// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Admin.IDP.Entity
{
    public class TempSegmentConfiguration : IEntityTypeConfiguration<TempSegment>
    {
        public void Configure(EntityTypeBuilder<TempSegment> entity)
        {
            entity.Property(e => e.szId).IsUnicode(false);

            entity.Property(e => e.szName).IsUnicode(false);
        }
    }
}
